pbk95120/Yeonda

frontend/src/App.tsx

[Chore] Test chart,js, react-chartjs-2

[Chore] Test chart,js, react-chartjs-2

---

backend/package-lock.json
backend/package.json

Install multer, socket.io

---

frontend/src/assets/images/Profile.svg
frontend/src/index.css

[Feat] noto sans bold style and profile svg add

---

backend/jest.config.mjs
backend/package-lock.json
backend/package.json
backend/src/types/controller.types.ts
backend/tsconfig.json

Install joi, supertest and some fixes

---

frontend/src/components/common/MainFooter.tsx
frontend/src/components/common/MainHeader.tsx
frontend/src/layout/Layout.tsx
frontend/src/main.tsx

[feat] footer(tabbar)

---

frontend/src/components/common/Button.tsx
frontend/src/components/common/Input.tsx
frontend/src/components/common/MainFooter.tsx
frontend/src/layout/Layout.tsx
frontend/src/pages/MyPage.tsx
frontend/tailwind.config.js
package-lock.json

Fe components

---

frontend/src/components/common/Button.tsx
frontend/src/components/common/MainFooter.tsx
frontend/src/components/common/Modal.tsx
frontend/src/layout/Layout.tsx
frontend/src/pages/MyPage.tsx

[fix]Button props

---

frontend/src/components/common/Modal.tsx

모달 사용법
1. 사용하는 페이지에 모달이 열렸는지 안 열렸는지 state 필요
2. Modal 에 isOpen props 전달
3. closeModal 함수도 closeModal props로 전달
4. 추가 스타일 className props활용
5. 자식컴포넌트 그냥 모달 태그 사이에다가 쓰면 됌

[Feat] Modal 구현

---

frontend/src/components/common/Button.tsx
frontend/src/components/common/Modal.tsx
frontend/src/components/common/Toast.tsx
frontend/src/pages/MyPage.tsx
frontend/src/utils/dcls.ts

모달 기본 모형
- props: purposeMsg , cautionMsg 추가
- 취소 확인 버튼 추가
- onClick props추가 확인버튼에 해당됌

[fix] modal v2

---

frontend/src/layout/Layout.tsx

[Fix] none footer main component size fix

---

frontend/package-lock.json
frontend/package.json

react-intersection-observer, framer-motion 설치

---

frontend/src/components/common/Input.tsx
frontend/src/components/common/Modal.tsx
frontend/src/pages/MyPage.tsx

[fix] Input.tsx style fix

---

frontend/src/components/common/MainHeader.tsx
frontend/src/components/common/Toast.tsx
frontend/src/main.tsx

[fix] header add logo& backbtn

---

frontend/src/components/common/MainHeader.tsx
frontend/src/layout/Layout.tsx
frontend/src/main.tsx

[fix] header writeDiary completebtn

---

backend/src/sockets/controller.ts
backend/src/sockets/database.ts
backend/src/sockets/index.ts
backend/src/sockets/middleware.ts
backend/src/sockets/util.ts

에러 통합 핸들러 생성, 트랜잭션 처리 추가, 채팅 읽음 처리 기능 추가

[Hotfix] chat 수정 및 기능 추가

---

backend/package-lock.json
backend/package.json
backend/src/app.ts
backend/src/index.ts
backend/src/sockets/controller.ts
backend/src/sockets/database.ts
backend/src/sockets/index.ts
backend/src/sockets/middleware.ts
backend/src/sockets/schemas.ts
backend/src/sockets/util.ts

[Refactor] Chat 1대1 채팅방 기능 구현 코드 수정 및 라이브러리 설치

---

frontend/src/api/diaries.api.ts
frontend/src/components/diaries/DiaryItem.tsx
frontend/src/components/diaries/FixTags.tsx
frontend/src/components/mypage/MyInfo.tsx
frontend/src/components/mypage/MyPref.tsx
frontend/src/hooks/diary/useDiaryChange.ts
frontend/src/pages/MyPage.tsx
frontend/src/pages/PreferencePage.tsx
frontend/src/types/type.ts

내일기 태그 수정 구현
내일기에서 태그창 너무 길게 나와서 접고 펼수있게 만들려고 함

[Feat] 내일기 태그 수정

---

frontend/src/api/socket.ts
frontend/src/components/chat/ChatProfile.tsx
frontend/src/hooks/chat/useChatList.ts
frontend/src/pages/ChatDetailPage.tsx

edit socket chat console

---

frontend/src/components/chat/ChatHeader.tsx
frontend/src/components/chat/ChatProfile.tsx
frontend/src/components/chat/ChatTextarea.tsx
frontend/src/components/chat/MyChatBubble.tsx
frontend/src/components/chat/UserDiary.tsx
frontend/src/components/diaries/DiaryItem.tsx
frontend/src/hooks/chat/useOtherDiary.ts
frontend/src/pages/ChatDetailPage.tsx
frontend/src/test/chat/ChatList.test.tsx
frontend/src/test/chat/ChatProfile.test.tsx

[Refactor] delete console log and update chat tag

---

frontend/src/hooks/chat/useChatList.ts
frontend/src/pages/ChatListPage.tsx

[Feat] no diary chat page update

---

frontend/index.html
frontend/src/main.tsx

[Refactor] update code spliting in routing , [Chore] meta tag update for seo
